%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function list = check_params_in(params_in)
%% returns list of fields for params_in (required by WIM2d.m)
%% and checks a given structure params_in that it has enough fields
list  = {'SCATMOD',...           int_prams
         'ADV_DIM',...
         'ADV_OPT',...
         'DO_CHECK_INIT',...
         'DO_CHECK_PROG',...
         'DO_CHECK_FINAL',...
         'BRK_OPT',...
         'STEADY',...
         'DO_ATTEN',...          int_prams
         'FSD_OPT',...
         'young',...             real_prams
         'drag_rp',...
         'viscoelastic_ws',...
         'CFL',...
         'duration_hours',...    real_prams
         'REF_Hs_ICE',...
         'MEX_OPT',...
         'OPT',...
         'DO_DISP',...
         'SV_BIN',...
         'SV_SPEC',...
         'SV_FIG',...
         'PLOT_INIT',...
         'PLOT_PROG',...
         'PLOT_FINAL',...
         'CHK_ATTEN',...
         'USE_ICE_VEL',...
         'DIAG1d',...
         'DIAG1d_OPT'};

   %% check input type
   if nargin==0
      return; %just give the list of required fields
   elseif ~isstruct(params_in)
      error('WIM2d.m: <<params_in>> should be a structure');
   end

   for j=1:length(list)
      if ~isfield(params_in,list{j});
         error(['WIM2d.m: <<params_in>> does not possess the field ',list{j}]);
      end
   end

return
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
